"""
Jaee Oh
Spring 2026

CS 5330 Computer Vision

Project 5.

Skeleton code was generated by Claude Code using the code structure of classes and functions given in the assignment page.
Claude AI was used for code review and debugging.
"""

import sys
import os
import glob
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader


# ── Class Definitions ────────────────────────────────────────────────────────


class MNISTNetwork(nn.Module):
    """Same CNN architecture as mnist_cnn.py — must match exactly to load saved weights."""

    def __init__(self):
        super(MNISTNetwork, self).__init__()

        # Must match the layer names used in mnist_cnn.py exactly
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=10, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=10, out_channels=20, kernel_size=5)
        self.dropout = nn.Dropout(p=0.5)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    # Computes a forward pass; returns log_softmax probabilities over 10 digit classes
    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), kernel_size=2))
        x = F.relu(F.max_pool2d(self.dropout(self.conv2(x)), kernel_size=2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        return F.log_softmax(self.fc2(x), dim=1)


# ── MNIST Test Set Functions ──────────────────────────────────────────────────


def load_model(path, device):
    """Loads a MNISTNetwork from a saved state dict file and sets it to eval mode."""
    model = MNISTNetwork().to(device)
    model.load_state_dict(torch.load(path, map_location=device))
    model.eval()
    print(f"Model loaded from '{path}'\n")
    return model


def load_test_data(batch_size=64):
    """Loads and returns the MNIST test DataLoader with the same normalization used in training."""
    transform = transforms.Compose(
        [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]
    )
    test_set = datasets.MNIST(
        root="./data", train=False, download=True, transform=transform
    )
    test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False)
    return test_loader


def predict_first_n(model, test_loader, device, n=10):
    """Runs the model on the first n examples and returns images, true labels, predictions, and probabilities."""
    images, labels = next(iter(test_loader))
    images, labels = images[:n], labels[:n]

    with torch.no_grad():
        output = model(images.to(device))
        probs = torch.exp(output).cpu()
        preds = probs.argmax(dim=1)

    return images, labels, preds, probs


def print_results_table(labels, preds, probs):
    """Prints a formatted table of index, true label, prediction, confidence, and correctness."""
    header = (
        f"{'Index':>6}  {'True':>5}  {'Pred':>5}  {'Confidence':>11}  {'Correct':>7}"
    )
    print(header)
    print("-" * len(header))
    for i in range(len(labels)):
        true = labels[i].item()
        pred = preds[i].item()
        confidence = probs[i][pred].item() * 100
        correct = "Yes" if pred == true else "No"
        print(f"{i:>6}  {true:>5}  {pred:>5}  {confidence:>10.2f}%  {correct:>7}")
    print()


def plot_first_nine(images, labels, preds, save_path="plot/first_nine_predictions.png"):
    """Plots the first 9 test digits in a 3x3 grid with true and predicted labels, and saves to file."""
    fig, axes = plt.subplots(3, 3, figsize=(7, 7))
    fig.suptitle("First 9 Test Set Digits — Predictions", fontsize=13)

    for i, ax in enumerate(axes.flat):
        ax.imshow(images[i].squeeze(), cmap="gray")
        true = labels[i].item()
        pred = preds[i].item()
        color = "green" if pred == true else "red"
        ax.set_title(f"True: {true}  Pred: {pred}", color=color, fontsize=10)
        ax.axis("off")

    plt.tight_layout()
    plt.savefig(save_path)
    print(f"Plot saved to '{save_path}'")
    plt.show()


# ── Custom Digit Functions ────────────────────────────────────────────────────


def load_custom_images(image_dir):
    """Loads all .jpg/.png images from a directory, sorted by filename.
    Returns a list of (filename, PIL Image) tuples."""
    paths = sorted(
        glob.glob(os.path.join(image_dir, "*.jpg"))
        + glob.glob(os.path.join(image_dir, "*.jpeg"))
        + glob.glob(os.path.join(image_dir, "*.png"))
    )

    if not paths:
        print(f"No images found in '{image_dir}'")
        sys.exit(1)

    images = [(os.path.basename(p), Image.open(p)) for p in paths]
    print(f"Found {len(images)} custom image(s) in '{image_dir}'")
    return images


def preprocess_image(pil_img):
    """Preprocesses a PIL image to match MNIST format:
    grayscale → resize 28x28 → invert (white digit on black) → normalize."""
    transform = transforms.Compose(
        [
            transforms.Grayscale(),  # ensure single channel
            transforms.Resize((28, 28)),  # force 28x28 regardless of crop size
            transforms.ToTensor(),  # [0,255] → [0.0,1.0]
            transforms.Lambda(
                lambda x: 1.0 - x
            ),  # invert: dark on white → white on black
            transforms.Normalize(
                (0.1307,), (0.3081,)
            ),  # same normalization as training
        ]
    )
    return transform(pil_img)


def predict_custom(model, raw_images, device):
    """Preprocesses and runs the model on a list of PIL images; returns predictions and probabilities."""
    tensors = [preprocess_image(img) for img in raw_images]
    batch = torch.stack(tensors).to(device)
    with torch.no_grad():
        output = model(batch)
        probs = torch.exp(output).cpu()
        preds = probs.argmax(dim=1)
    return preds, probs


def print_custom_results_table(filenames, true_labels, preds, probs):
    """Prints a formatted results table for custom digits with accuracy summary."""
    header = (
        f"{'File':<25}  {'True':>5}  {'Pred':>5}  {'Confidence':>11}  {'Correct':>7}"
    )
    print(header)
    print("-" * len(header))
    correct_count = 0
    for fname, true, pred, prob in zip(filenames, true_labels, preds, probs):
        confidence = prob[pred.item()].item() * 100
        correct = "Yes" if pred.item() == true else "No"
        if pred.item() == true:
            correct_count += 1
        print(
            f"{fname:<25}  {true:>5}  {pred.item():>5}  {confidence:>10.2f}%  {correct:>7}"
        )
    print(
        f"\nAccuracy: {correct_count}/{len(filenames)} "
        f"({correct_count / len(filenames) * 100:.1f}%)\n"
    )


def plot_custom_results(
    raw_images,
    filenames,
    true_labels,
    preds,
    probs,
    save_path="plot/custom_digit_results.png",
):
    """Displays all custom digits in a grid with true label, prediction, and confidence.
    Saves the plot to file."""
    n = len(raw_images)
    cols = 5
    rows = (n + cols - 1) // cols

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 2.5, rows * 3))
    axes = np.array(axes).reshape(-1)

    for i in range(len(axes)):
        ax = axes[i]
        if i < n:
            ax.imshow(raw_images[i].convert("L"), cmap="gray")
            pred = preds[i].item()
            true = true_labels[i]
            confidence = probs[i][pred].item() * 100
            color = "green" if pred == true else "red"
            ax.set_title(
                f"True: {true}  Pred: {pred}\n{confidence:.1f}%",
                color=color,
                fontsize=9,
            )
        ax.axis("off")

    fig.suptitle("Custom Handwritten Digit Predictions", fontsize=13)
    plt.tight_layout()
    plt.savefig(save_path)
    print(f"Plot saved to '{save_path}'")
    plt.show()


# ── Main Function ─────────────────────────────────────────────────────────────


def main(argv):
    # Usage: python3 evaluate.py [model_path] [custom_image_dir]
    # Example: python3 evaluate.py mnist_cnn.pth my_digits/
    model_path = argv[1] if len(argv) > 1 else "model/mnist_cnn.pth"
    image_dir = argv[2] if len(argv) > 2 else "handwritten"

    # Select compute device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}\n")

    # Load the saved model
    model = load_model(model_path, device)

    # ── Part 1: MNIST test set ────────────────────────────────────────────────
    print("=" * 50)
    print("Part 1: MNIST Test Set — First 10 Examples")
    print("=" * 50)

    test_loader = load_test_data()
    images, labels, preds, probs = predict_first_n(model, test_loader, device, n=10)

    print_results_table(labels, preds, probs)
    plot_first_nine(images, labels, preds)

    # ── Part 2: Custom handwritten digits ─────────────────────────────────────
    print("=" * 50)
    print("Part 2: Custom Handwritten Digits")
    print("=" * 50)

    named_images = load_custom_images(image_dir)
    filenames = [name for name, _ in named_images]
    raw_images = [img for _, img in named_images]

    # Extract true label from filename — expects format like handwritten_3.jpg → 3
    true_labels = [int(os.path.splitext(f)[0].split("_")[-1]) for f in filenames]

    preds, probs = predict_custom(model, raw_images, device)

    print_custom_results_table(filenames, true_labels, preds, probs)
    plot_custom_results(raw_images, filenames, true_labels, preds, probs)

    return


if __name__ == "__main__":
    main(sys.argv)
