"""
Jaee Oh
Spring 2026

CS 5330 Computer Vision

Project 5.

Skeleton code was generated by Claude Code using the code structure of classes and functions given in the assignment page.
Claude AI was used for code review and debugging.
"""

import sys
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader


class MNISTNetwork(nn.Module):
    """
    CNN for MNIST digit classification with the following architecture:
      Conv(10, 5x5) → MaxPool(2x2) + ReLU
      Conv(20, 5x5) → Dropout(0.5) → MaxPool(2x2) + ReLU
      Flatten → Linear(320 → 50) + ReLU
      Linear(50 → 10) + log_softmax
    """

    def __init__(self):
        super(MNISTNetwork, self).__init__()

        # First convolution layer: 1 input channel, 10 filters, 5x5 kernel
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=10, kernel_size=5)

        # Second convolution layer: 10 input channels, 20 filters, 5x5 kernel
        self.conv2 = nn.Conv2d(in_channels=10, out_channels=20, kernel_size=5)

        # Dropout layer with 50% drop rate (applied after conv2)
        self.dropout = nn.Dropout(p=0.5)

        # Fully connected layer 1: 320 → 50
        # 320 = 20 filters × 4 × 4 (spatial size after two 2x2 pools on 28x28 input)
        self.fc1 = nn.Linear(320, 50)

        # Fully connected layer 2 (output): 50 → 10 classes
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        # Conv layer 1 (10 × 5x5) → MaxPool (2x2) → ReLU
        x = F.relu(F.max_pool2d(self.conv1(x), kernel_size=2))

        # Conv layer 2 (20 × 5x5) → Dropout (0.5) → MaxPool (2x2) → ReLU
        x = F.relu(F.max_pool2d(self.dropout(self.conv2(x)), kernel_size=2))

        # Flatten from (batch, 20, 4, 4) → (batch, 320)
        x = x.view(-1, 320)

        # Fully connected layer 1 → 50 nodes → ReLU
        x = F.relu(self.fc1(x))

        # Fully connected output layer → 10 nodes → log_softmax
        x = F.log_softmax(self.fc2(x), dim=1)

        return x


def load_data(batch_size=64):
    """Downloads MNIST and returns train and test DataLoaders."""
    transform = transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,)),  # MNIST global mean & std
        ]
    )

    train_set = datasets.MNIST(
        root="./data", train=True, download=True, transform=transform
    )
    test_set = datasets.MNIST(
        root="./data", train=False, download=True, transform=transform
    )

    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False)

    print(f"Training samples : {len(train_set)}")
    print(f"Test samples     : {len(test_set)}\n")
    return train_loader, test_loader


def train_network(model, train_loader, optimizer, device, epoch):
    """Runs one full training epoch using NLLLoss; prints loss every 200 batches."""
    model.train()
    total_loss, correct, total = 0.0, 0, 0

    for batch_idx, (images, labels) in enumerate(train_loader):
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        output = model(images)  # log_softmax output
        loss = F.nll_loss(output, labels)  # pairs with log_softmax
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)
        preds = output.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += images.size(0)

        if (batch_idx + 1) % 200 == 0:
            print(
                f"  Epoch {epoch} [{batch_idx+1}/{len(train_loader)}] "
                f"Loss: {loss.item():.4f}"
            )

    avg_loss = total_loss / total
    accuracy = correct / total
    return avg_loss, accuracy


def evaluate_network(model, test_loader, device):
    """Evaluates the model on the test set; returns average loss and accuracy."""
    model.eval()
    total_loss, correct, total = 0.0, 0, 0

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            output = model(images)
            total_loss += F.nll_loss(output, labels, reduction="sum").item()
            preds = output.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += images.size(0)

    avg_loss = total_loss / total
    accuracy = correct / total
    return avg_loss, accuracy


def plot_first_six(test_loader, save_path="plot/first_six_digits.png"):
    """Plots and saves the first six example digits from the test set."""
    images, labels = next(iter(test_loader))
    images, labels = images[:6], labels[:6]

    fig, axes = plt.subplots(1, 6, figsize=(12, 2))
    fig.suptitle("First 6 Digits from the Test Set", fontsize=13)
    for i, ax in enumerate(axes):
        ax.imshow(images[i].squeeze(), cmap="gray")
        ax.set_title(f"Label: {labels[i].item()}")
        ax.axis("off")
    plt.tight_layout()
    plt.savefig(save_path)
    print(f"First six digits plot saved to '{save_path}'")
    plt.show()


def plot_training_curves(
    train_losses,
    test_losses,
    train_accs,
    test_accs,
    save_path="plot/training_curves.png",
):
    """Plots loss and accuracy curves over all training epochs and saves to file."""
    epochs = range(1, len(train_losses) + 1)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(epochs, train_losses, label="Train")
    ax1.plot(epochs, test_losses, label="Test")
    ax1.set_title("NLL Loss")
    ax1.set_xlabel("Epoch")
    ax1.legend()

    ax2.plot(epochs, [a * 100 for a in train_accs], label="Train")
    ax2.plot(epochs, [a * 100 for a in test_accs], label="Test")
    ax2.set_title("Accuracy (%)")
    ax2.set_xlabel("Epoch")
    ax2.legend()

    plt.tight_layout()
    plt.savefig(save_path)
    print(f"Training curves saved to '{save_path}'")
    plt.show()


def save_model(model, path="mnist_cnn.pth"):
    """Saves the trained model's state dict to a file."""
    torch.save(model.state_dict(), path)
    print(f"\nModel saved to '{path}'")


def load_model(path="mnist_cnn.pth", device="cpu"):
    """Loads and returns a MNISTNetwork from a saved state dict file."""
    model = MNISTNetwork().to(device)
    model.load_state_dict(torch.load(path, map_location=device))
    model.eval()
    print(f"Model loaded from '{path}'")
    return model


def main(argv):
    # Usage: python mnist_cnn.py [epochs] [learning_rate]
    # Example: python mnist_cnn.py 10 0.001
    epochs = int(argv[1]) if len(argv) > 1 else 5
    lr = float(argv[2]) if len(argv) > 2 else 0.01

    batch_size = 64
    model_path = "model/mnist_cnn.pth"

    # Select compute device (GPU/CPU)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device  : {device}")
    print(f"Epochs  : {epochs}  |  LR: {lr}  |  Batch: {batch_size}\n")

    # Load MNIST data
    train_loader, test_loader = load_data(batch_size)

    # Build model and optimizer
    model = MNISTNetwork().to(device)
    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)

    print(model, "\n")

    # Plot the first six digits from the test set
    plot_first_six(test_loader)

    # Training loop — train then evaluate each epoch
    train_losses, test_losses = [], []
    train_accs, test_accs = [], []

    for epoch in range(1, epochs + 1):
        tr_loss, tr_acc = train_network(model, train_loader, optimizer, device, epoch)
        te_loss, te_acc = evaluate_network(model, test_loader, device)

        train_losses.append(tr_loss)
        test_losses.append(te_loss)
        train_accs.append(tr_acc)
        test_accs.append(te_acc)

        print(
            f"Epoch {epoch}/{epochs} → "
            f"Train Loss: {tr_loss:.4f}  Acc: {tr_acc*100:.2f}% | "
            f"Test  Loss: {te_loss:.4f}  Acc: {te_acc*100:.2f}%\n"
        )

    # Plot training curves
    plot_training_curves(train_losses, test_losses, train_accs, test_accs)

    # Save the trained network to file
    save_model(model, model_path)

    return


if __name__ == "__main__":
    main(sys.argv)
